# Generated by Django 5.1.3 on 2025-02-12 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_giornalista_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornalista',
            name='nascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 58, 17, 11763)),
        ),
    ]
