# Generated by Django 5.1.3 on 2025-02-12 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_giornalista_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornalista',
            name='nascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 10, 44, 20, 243781)),
        ),
    ]
