# Generated by Django 5.1.3 on 2025-03-19 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_giornalista_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornalista',
            name='nascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 19, 11, 10, 46, 489876)),
        ),
    ]
