# Generated by Django 5.1.3 on 2025-02-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=30)),
                ('descrizione', models.TextField(max_length=40)),
                ('data_inizio', models.DateField(auto_now=True)),
                ('data_fine', models.DateField(auto_now=True)),
                ('posti_disponibili', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
