# Generated by Django 5.1.3 on 2025-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corso',
            options={'verbose_name': 'Corso', 'verbose_name_plural': 'Corsi'},
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='corso',
            name='posti_disponibili',
            field=models.IntegerField(blank=True),
        ),
    ]
